sudo: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    packages:
    - shellcheck

services:
  - docker

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker build -t gluster/client ./gluster-client/
- docker run -it --name client gluster/client rpm -qa | grep gluster
- docker build -t gluster/centos ./CentOS/
- docker run -d --name gcentos --privileged gluster/centos
- sleep 10
- docker exec -it gcentos systemctl is-active glusterd
- docker stop gcentos
- docker rm gcentos
- sudo mkdir -p /home/centos-glusterd
- sudo mkdir -p /home/centos-gluster-etc
- sudo mkdir -p /home/centos-gluster-log
- docker run -d --name gcentos -v /home/centos-glusterd:/var/lib/glusterd/:z -v /home/centos-gluster-etc:/etc/glusterfs:z -v /home/centos-gluster-log:/var/log/glusterfs --privileged gluster/centos
- sleep 10
- docker exec -it gcentos systemctl is-active glusterd
- docker stop gcentos
- docker rm gcentos
- docker build -t gluster/fedora ./Fedora/
- docker run -d --name gfedora --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro gluster/fedora
- sleep 10
- docker exec -it gfedora systemctl is-active glusterd
- docker stop gfedora
- docker rm gfedora
- sudo mkdir -p /home/fedora-glusterd
- sudo mkdir -p /home/fedora-gluster-etc
- sudo mkdir -p /home/fedora-gluster-log
- docker run -d --name gfedora -v /home/fedora-glusterd:/var/lib/glusterd/:z -v /home/fedora-gluster-etc:/etc/glusterfs:z -v /home/fedora-gluster-log:/var/log/glusterfs -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged gluster/fedora
- sleep 10
- docker exec -it gfedora systemctl is-active glusterd
- docker stop gfedora
- docker rm gfedora
- docker build -t gluster/s3object ./gluster-s3object/CentOS/docker-gluster-s3/
- docker run -d --name s3object --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -e S3_ACCOUNT=vol -e S3_USER="admin" -e S3_PASSWORD="redhat" gluster/s3object
- sleep 10
- docker exec -it s3object systemctl is-active swift-object

script:
- make test
